// <auto-generated />
using System;
using CheckPay.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheckPay.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414090235_CustomerCodeUniqueExcludeSoftDeleted")]
    partial class CustomerCodeUniqueExcludeSoftDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheckPay.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.CheckRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("account_address");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("account_type");

                    b.Property<bool>("AchDebitSucceeded")
                        .HasColumnType("boolean")
                        .HasColumnName("ach_debit_succeeded");

                    b.Property<DateTime?>("AchDebitSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ach_debit_succeeded_at");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<decimal>("CheckAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("check_amount");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_number");

                    b.Property<string>("CheckNumberMicr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_number_micr");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CustomerCompanyNewRelationshipWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("customer_company_new_relationship_warning");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("CustomerMasterMismatchWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("customer_master_mismatch_warning");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ForMemo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_memo");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("InvoiceNumbers")
                        .HasColumnType("text")
                        .HasColumnName("invoice_numbers");

                    b.Property<string>("MicrLineRaw")
                        .HasColumnType("text")
                        .HasColumnName("micr_line_raw");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OcrResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("ocr_result_id");

                    b.Property<string>("PayToOrderOf")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pay_to_order_of");

                    b.Property<string>("PaymentPeriodText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_period_text");

                    b.Property<string>("RoutingNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("routing_number");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AchDebitSucceeded")
                        .HasDatabaseName("ix_check_records_ach_debit_succeeded");

                    b.HasIndex("CheckNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_check_records_check_number");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_check_records_customer_id");

                    b.HasIndex("OcrResultId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_check_records_status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_check_records_submitted_at");

                    b.ToTable("check_records", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExpectedAccountAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("expected_account_address");

                    b.Property<string>("ExpectedAccountHolderName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("expected_account_holder_name");

                    b.Property<string>("ExpectedBankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("expected_bank_name");

                    b.Property<string>("ExpectedCompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("expected_company_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_authorized");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_customer_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.CustomerCompanyName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_company_names_customer_id");

                    b.HasIndex("CustomerId", "CompanyName")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_company_names_customer_company");

                    b.ToTable("customer_company_names", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.DebitRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_reference");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_number");

                    b.Property<Guid?>("CheckRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("debit_amount");

                    b.Property<DateTime>("DebitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("debit_date");

                    b.Property<string>("DebitStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("debit_status");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ScanImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scan_image_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CheckNumber")
                        .HasDatabaseName("ix_debit_records_check_number");

                    b.HasIndex("CheckRecordId")
                        .IsUnique();

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_debit_records_customer_id");

                    b.HasIndex("DebitStatus")
                        .HasDatabaseName("ix_debit_records_debit_status");

                    b.ToTable("debit_records", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.OcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AzureConfidenceScores")
                        .HasColumnType("jsonb")
                        .HasColumnName("azure_confidence_scores");

                    b.Property<string>("AzureErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("azure_error_message");

                    b.Property<string>("AzureRawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("azure_raw_result");

                    b.Property<string>("AzureStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("azure_status");

                    b.Property<string>("ConfidenceScores")
                        .HasColumnType("jsonb")
                        .HasColumnName("confidence_scores");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("RawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ocr_results_status");

                    b.ToTable("ocr_results", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.OcrTrainingSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAchExtensionJson")
                        .HasColumnType("text")
                        .HasColumnName("correct_ach_extension_json");

                    b.Property<decimal?>("CorrectAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("correct_amount");

                    b.Property<string>("CorrectBankReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correct_bank_reference");

                    b.Property<string>("CorrectCheckNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correct_check_number");

                    b.Property<DateTime?>("CorrectDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correct_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OcrAchExtensionJson")
                        .HasColumnType("text")
                        .HasColumnName("ocr_ach_extension_json");

                    b.Property<decimal?>("OcrAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ocr_amount");

                    b.Property<string>("OcrBankReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ocr_bank_reference");

                    b.Property<string>("OcrCheckNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ocr_check_number");

                    b.Property<DateTime?>("OcrDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocr_date");

                    b.Property<string>("OcrRawResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocr_raw_response");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ocr_training_samples_created_at");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("ix_ocr_training_samples_document_type");

                    b.ToTable("ocr_training_samples", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entra_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntraId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CheckPay.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.CheckRecord", b =>
                {
                    b.HasOne("CheckPay.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckPay.Domain.Entities.OcrResult", "OcrResult")
                        .WithMany()
                        .HasForeignKey("OcrResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("OcrResult");
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.CustomerCompanyName", b =>
                {
                    b.HasOne("CheckPay.Domain.Entities.Customer", "Customer")
                        .WithMany("CompanyNames")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.DebitRecord", b =>
                {
                    b.HasOne("CheckPay.Domain.Entities.CheckRecord", "CheckRecord")
                        .WithOne("DebitRecord")
                        .HasForeignKey("CheckPay.Domain.Entities.DebitRecord", "CheckRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CheckPay.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckRecord");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.CheckRecord", b =>
                {
                    b.Navigation("DebitRecord");
                });

            modelBuilder.Entity("CheckPay.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CompanyNames");
                });
#pragma warning restore 612, 618
        }
    }
}
